// Generated by CoffeeScript 1.3.3
(function() {
  var SimpleHtml5DraggableResizable;

  SimpleHtml5DraggableResizable = (function() {

    function SimpleHtml5DraggableResizable(element_, options) {
      var opt, _i, _len, _ref;
      this.element_ = element_;
      this.options = $.extend({}, options);
      this.element = $(this.element_);
      this.element = (($(this.element_)).wrap('<div class="resizable">')).parent();
      _ref = ['mouseover', 'drag', 'mouseout', 'dragstart', 'dragend'];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        opt = _ref[_i];
        this.element.on(opt, this[opt]);
      }
    }

    SimpleHtml5DraggableResizable.prototype.mouseover = function() {
      return ($(this)).toggleClass('selectedObject');
    };

    SimpleHtml5DraggableResizable.prototype.mouseout = function() {
      return ($(this)).toggleClass('selectedObject');
    };

    SimpleHtml5DraggableResizable.prototype.dragstart = function(ev) {
      return this.style.opacity = 0.4;
    };

    SimpleHtml5DraggableResizable.prototype.drag = function(ev) {
      this.style.opacity = 0.4;
      this.style.left = ev.x + "px";
      this.style.top = ev.y + "px";
      return this.style.position = "absolute";
    };

    SimpleHtml5DraggableResizable.prototype.dragend = function(ev) {
      return this.style.opacity = 1;
    };

    return SimpleHtml5DraggableResizable;

  })();

  (function($) {
    return $.fn.simpleHtml5DraggableResizable = function(options) {
      var resizable;
      if (options == null) {
        options = {
          draggable: true
        };
      }
      return resizable = new SimpleHtml5DraggableResizable(this, options);
    };
  })($);

}).call(this);
